### ISSUE TITLE
Create UART ISR

### ISSUE THREAD

**Issue by mgreci** [jacobnash/SNAKE#1]
Create the ISR for UART (on UART 1) so that keys pressed go to MAILBOX so the snake will move.

**Comment by jacobnash** [comment]
Not really and ISR needed. I dont think that it is neccesary given the Circumstances. Just using Mailbox.

**Comment by mgreci** [comment]
UART is steady state, continually overwriting MAILBOX. However, something will need to determine if Move_Snake should be called or something else. It cannot be up to the Snake to decide to stop the game, change hardness.
