### ISSUE TITLE
Random Number generator

### ISSUE THREAD

**Issue by jacobnash** [jacobnash/SNAKE#10]
Get a Random number. with constraints, the Values wanted, and offset from 0 Pass as (byte)offset(byte)Value. IE I want a number fom 10 to 100 I sent 0A5A

**Comment by mgreci** [comment]
do you mean 10 -> 100 would get 0x0A64? This is sending 10 and 100. I think we can simply the generator by saying rand(x,y) and get number 'A' where x <= 'A' <= y
