### ISSUE TITLE
Reorganize what handles input chars 

### ISSUE THREAD

**Issue by mgreci** [jacobnash/SNAKE#15]
Currently Move_Snake only handles what is in the MAILBOX. Also ISR_Timer1 should not handle redirecting. Create a new place to handle what is in the mailbox and use Move_Snake, change speed, or start/stop game

**Comment by mgreci** [comment]
"0" means 1 second speed. Then "1" means 0.1 seconds period and "9" means 0.9 seconds period.

**Comment by jacobnash** [comment]
I think that is what you wanted. I think there should be something that checks speed, and then updates the PR1, MAybe this is why we may need two timers?

**Comment by mgreci** [comment]
We can stop the timer, then load a new period and start the timer again. No problems there.

Thank you,
Matthew Greci

On May 4, 2015, at 9:37 AM, Jacob Nash <notifications@github.com<mailto:notifications@github.com>> wrote:

I think that is what you wanted. I think there should be something that checks speed, and then updates the PR1, MAybe this is why we may need two timers?

##

**Comment by mgreci** [comment]
input 0-9 changes speed correctly. Elapsed timer is updated with the timer. maybe need a second timer or try to do a scaling thing.
Read PR1, determine how many cycles at this period to wait to increment elapsed time.
