### ISSUE TITLE
You get sprung

### ISSUE THREAD

**Issue by mgreci** [jacobnash/SNAKE#16]
create a function to print GAMEOVER in multiple spots to say its game over.
Would be nice to do:
...
bal GAMEOVER
nop
...

**Comment by jacobnash** [comment]
Is this needed? like a have to have?

**Comment by mgreci** [comment]
No not really. I just like the title

Thank you,
Matthew Greci

On May 4, 2015, at 9:38 AM, Jacob Nash <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this needed? like a have to have?

##
