### ISSUE TITLE
Enable JKHLC, Buttons, 1-9 hardness

### ISSUE THREAD

**Issue by jacobnash** [jacobnash/SNAKE#9]
Straight forward determine if what needs to go into mail box, Level Harness, or If the game is active.

**Comment by mgreci** [comment]
What defines "hardness"? speed? non-responsive snake? Goes back to idea of a single MAILBOX redirecton. Read MAILBOX, branch to correct thing (Move_Snake or Stop game or Change hardness)

**Comment by mgreci** [comment]
Buttons are no longer required. "0" means 1 second speed. Then "1" means 0.1 seconds period and "9" means 0.9 seconds period.

**Comment by mgreci** [comment]
duplicate
